//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Products.Library.Contracts
{

  [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
  [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.sample.com/ProductService/", ConfigurationName = "ProductsPortType")]
  public interface ProductsPortType
  {

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.sample.com/ProductService/GetProducts", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task<GetProductsResponse1> GetProductsAsync(GetProductsRequest1 request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://www.sample.com/ProductService/GetProductDetails", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task<GetProductDetailsResponse1> GetProductDetailsAsync(GetProductDetailsRequest1 request);
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sample.com/ProductService/")]
  public partial class GetProductsRequest
  {
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sample.com/ProductService/")]
  public partial class GetProductsResponse
  {

    private object idField;

    private object nameField;

    private object thumbnailUrlField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public object id
    {
      get
      {
        return this.idField;
      }
      set
      {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public object name
    {
      get
      {
        return this.nameField;
      }
      set
      {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public object thumbnailUrl
    {
      get
      {
        return this.thumbnailUrlField;
      }
      set
      {
        this.thumbnailUrlField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
  [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
  [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
  public partial class GetProductsRequest1
  {

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.sample.com/ProductService/", Order = 0)]
    public GetProductsRequest GetProductsRequest;

    public GetProductsRequest1()
    {
    }

    public GetProductsRequest1(GetProductsRequest GetProductsRequest)
    {
      this.GetProductsRequest = GetProductsRequest;
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
  [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
  [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
  public partial class GetProductsResponse1
  {

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.sample.com/ProductService/", Order = 0)]
    public GetProductsResponse GetProductsResponse;

    public GetProductsResponse1()
    {
    }

    public GetProductsResponse1(GetProductsResponse GetProductsResponse)
    {
      this.GetProductsResponse = GetProductsResponse;
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sample.com/ProductService/")]
  public partial class GetProductDetailsRequest
  {

    private object idField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public object id
    {
      get
      {
        return this.idField;
      }
      set
      {
        this.idField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sample.com/ProductService/")]
  public partial class GetProductDetailsResponse
  {

    private object idField;

    private object nameField;

    private object descriptionField;

    private decimal priceField;

    private object thumbnailUrlField;

    private GetProductDetailsResponseProductImageUrls[] productImageUrlsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public object id
    {
      get
      {
        return this.idField;
      }
      set
      {
        this.idField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public object name
    {
      get
      {
        return this.nameField;
      }
      set
      {
        this.nameField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public object description
    {
      get
      {
        return this.descriptionField;
      }
      set
      {
        this.descriptionField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
    public decimal price
    {
      get
      {
        return this.priceField;
      }
      set
      {
        this.priceField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
    public object thumbnailUrl
    {
      get
      {
        return this.thumbnailUrlField;
      }
      set
      {
        this.thumbnailUrlField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("productImageUrls", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
    public GetProductDetailsResponseProductImageUrls[] productImageUrls
    {
      get
      {
        return this.productImageUrlsField;
      }
      set
      {
        this.productImageUrlsField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sample.com/ProductService/")]
  public partial class GetProductDetailsResponseProductImageUrls
  {

    private object productImageUrlField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public object productImageUrl
    {
      get
      {
        return this.productImageUrlField;
      }
      set
      {
        this.productImageUrlField = value;
      }
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
  [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
  [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
  public partial class GetProductDetailsRequest1
  {

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.sample.com/ProductService/", Order = 0)]
    public GetProductDetailsRequest GetProductDetailsRequest;

    public GetProductDetailsRequest1()
    {
    }

    public GetProductDetailsRequest1(GetProductDetailsRequest GetProductDetailsRequest)
    {
      this.GetProductDetailsRequest = GetProductDetailsRequest;
    }
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
  [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
  [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
  public partial class GetProductDetailsResponse1
  {

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.sample.com/ProductService/", Order = 0)]
    public GetProductDetailsResponse GetProductDetailsResponse;

    public GetProductDetailsResponse1()
    {
    }

    public GetProductDetailsResponse1(GetProductDetailsResponse GetProductDetailsResponse)
    {
      this.GetProductDetailsResponse = GetProductDetailsResponse;
    }
  }

  [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
  public interface ProductsPortTypeChannel : ProductsPortType, System.ServiceModel.IClientChannel
  {
  }

  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
  public partial class ProductsPortTypeClient : System.ServiceModel.ClientBase<ProductsPortType>, ProductsPortType
  {

    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

    public ProductsPortTypeClient() :
            base(ProductsPortTypeClient.GetDefaultBinding(), ProductsPortTypeClient.GetDefaultEndpointAddress())
    {
      this.Endpoint.Name = EndpointConfiguration.ProductsSoapHttpPort.ToString();
      ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public ProductsPortTypeClient(EndpointConfiguration endpointConfiguration) :
            base(ProductsPortTypeClient.GetBindingForEndpoint(endpointConfiguration), ProductsPortTypeClient.GetEndpointAddress(endpointConfiguration))
    {
      this.Endpoint.Name = endpointConfiguration.ToString();
      ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public ProductsPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
            base(ProductsPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
      this.Endpoint.Name = endpointConfiguration.ToString();
      ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public ProductsPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
            base(ProductsPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
      this.Endpoint.Name = endpointConfiguration.ToString();
      ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public ProductsPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetProductsResponse1> ProductsPortType.GetProductsAsync(GetProductsRequest1 request)
    {
      return base.Channel.GetProductsAsync(request);
    }

    public System.Threading.Tasks.Task<GetProductsResponse1> GetProductsAsync(GetProductsRequest GetProductsRequest)
    {
      GetProductsRequest1 inValue = new GetProductsRequest1();
      inValue.GetProductsRequest = GetProductsRequest;
      return ((ProductsPortType)(this)).GetProductsAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetProductDetailsResponse1> ProductsPortType.GetProductDetailsAsync(GetProductDetailsRequest1 request)
    {
      return base.Channel.GetProductDetailsAsync(request);
    }

    public System.Threading.Tasks.Task<GetProductDetailsResponse1> GetProductDetailsAsync(GetProductDetailsRequest GetProductDetailsRequest)
    {
      GetProductDetailsRequest1 inValue = new GetProductDetailsRequest1();
      inValue.GetProductDetailsRequest = GetProductDetailsRequest;
      return ((ProductsPortType)(this)).GetProductDetailsAsync(inValue);
    }

    public virtual System.Threading.Tasks.Task OpenAsync()
    {
      return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }

    public virtual System.Threading.Tasks.Task CloseAsync()
    {
      return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }

    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
      if ((endpointConfiguration == EndpointConfiguration.ProductsSoapHttpPort))
      {
        System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
        result.MaxBufferSize = int.MaxValue;
        result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
        result.MaxReceivedMessageSize = int.MaxValue;
        result.AllowCookies = true;
        result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
        return result;
      }
      throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }

    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
      if ((endpointConfiguration == EndpointConfiguration.ProductsSoapHttpPort))
      {
        return new System.ServiceModel.EndpointAddress("https://www.sample.com/ProductService/");
      }
      throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }

    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
      return ProductsPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.ProductsSoapHttpPort);
    }

    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
      return ProductsPortTypeClient.GetEndpointAddress(EndpointConfiguration.ProductsSoapHttpPort);
    }

    public enum EndpointConfiguration
    {

      ProductsSoapHttpPort,
    }
  }
}